apiVersion: apps/v1
kind: Deployment
metadata:
  name: techtrends
  namespace: sandbox
  labels:
    app: techtrends
    tag: latest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: techtrends
      tag: latest
  template:
    metadata:
      labels:
        app: techtrends
        tag: latest
    spec:
      containers:
      - name: techtrends
        image: rljdavies/tech-trends:latest
        resources:
          requests:
            cpu: 250m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 128Mi
        ports:
        - containerPort: 3111
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3111
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3111