namespace:
  name: sandbox
service:
  port: 4111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP
image:
  repository: rljdavies/tech-trends
  tag: latest
  pullPolicy: IfNotPresent
replicaCount: 1
resources:
  requests:
    cpu: 250m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 128Mi
containerPort: 3111
livenessProbe:
  port: 3111
  path: /healthz
readinessProbe:
  port: 3111
  path: /healthz
